[hosts.book]
platform = "x86_64"
version = "24.11"

[hosts.ozpc]
platform = "x86_64"
version = "24.11"

[users.oz]
home-manager = true

[sources.stylix]
type = "git"
url = "github:danth/stylix"
ref = "release-24.11"
commit = "9015d5d0d5d100f849129c43d257b827d300b089"