[package]
name = "lazy"
version = "0.1.0"
edition = "2021"
include = ["init/**"]

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.23", features = ["derive"] }
semver = "1.0.25"
sha2 = "0.10.8"
strsim = "0.11.1"
url = "2.5.4"
xdg = "2.5.2"
