[package]
name = "sysconf"
version = "0.0.1"
edition = "2021"
include = ["init/**"]

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
dirs = "5.0.1"
git2 = "0.19.0"
indexmap = "1.9.1"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
thiserror = "2.0.9"
xdg = "2.5.2"